options = trainingOptions('sgdm', ...
    'LearnRateSchedule','piecewise', ...
    'InitialLearnRate',0.001, ...
    'MaxEpochs',20, ...
    'MiniBatchSize',128, ...
    'ValidationData', {valData, valLabels}, ...
    'ValidationFrequency', 50, ...
    'Plots','training-progress');